name: em212
channels:
  - conda-forge
dependencies:
  - python=3.6
  - numpy
  - geopandas
  - matplotlib
  - pandas
  - seaborn
  - rise
  - pytest=4.0.0
  - statsmodels
  - scikit-learn
  - census
  - jupyterlab
  - jupyter
  - xlrd
  - papermill
  - ipykernel
  - jupyter_nbextensions_configurator
  - wordcloud
  - census
  - missingno
  - us
  - pip
  - pip:
    - jupyter-contrib-nbextensions
