name: paul-ww
channels:
  - conda-forge
dependencies:
  - python=3.6
  - numpy
  - geopandas
  - matplotlib
  - pandas
  - seaborn
  - rise
  - pytest=4.0.0
  - statsmodels
  - scikit-learn
  - jupyterlab
  - jupyter
  - xlrd
  - papermill
  - ipykernel
  - jupyter_nbextensions_configurator
  - pip
  - math
  - pickle
  - requests
  - zipfile
  - glob
  - datetime
  - io
  - re
  - pip:
    - jupyter-contrib-nbextensions
